**Feature Scaling**

In [2]:
import pandas as pd
from scipy import stats
import numpy as np

In [4]:
df=pd.read_csv("datasets/bmi.csv")

In [5]:
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [6]:
df.dropna()

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [7]:
max_vals = df[["Height", "Weight"]].max()
max_vals

Height    199
Weight    160
dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()
df_minmax = pd.DataFrame(
    scaler.fit_transform(df[["Height", "Weight"]]),
    columns=["Height", "Weight"]
)
df_minmax.head()

     Height    Weight
0  0.576271  0.418182
1  0.830508  0.336364
2  0.762712  0.545455
3  0.932203  0.490909
4  0.152542  0.100000

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()
df_standard = pd.DataFrame(
    scaler.fit_transform(df[["Height", "Weight"]]),
    columns=["Height", "Weight"]
)
df_standard.head()

     Height    Weight
0  0.247939 -0.309117
1  1.164872 -0.587322
2  0.920357  0.123647
3  1.531645 -0.061823
4 -1.280283 -1.391027

In [12]:
from sklearn.preprocessing import Normalizer

In [13]:
scaler = Normalizer()
df_normalized = pd.DataFrame(
    scaler.fit_transform(df[["Height", "Weight"]]),
    columns=["Height", "Weight"]
)
df_normalized.head()

     Height    Weight
0  0.875578  0.483077
1  0.908381  0.418144
2  0.859536  0.511075
3  0.882353  0.470588
4  0.925448  0.378875

In [14]:
from sklearn.preprocessing import MaxAbsScaler

In [15]:
scaler = MaxAbsScaler()
df_maxabs = pd.DataFrame(
    scaler.fit_transform(df[["Height", "Weight"]]),
    columns=["Height", "Weight"]
)
df_maxabs.head()

     Height   Weight
0  0.874372  0.60000
1  0.949749  0.54375
2  0.929648  0.68750
3  0.979899  0.65000
4  0.748744  0.38125

In [16]:
from sklearn.preprocessing import RobustScaler

In [17]:
scaler = RobustScaler()
df_robust = pd.DataFrame(
    scaler.fit_transform(df[["Height", "Weight"]]),
    columns=["Height", "Weight"]
)
df_robust.head()

     Height    Weight
0  0.125000 -0.178571
1  0.660714 -0.339286
2  0.517857  0.071429
3  0.875000 -0.035714
4 -0.767857 -0.803571

In [18]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import mutual_info_regression
from sklearn.feature_selection import chi2

In [20]:
df=pd.read_csv('datasets/titanic_dataset.csv')

In [21]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [22]:
df.shape

(891, 12)

In [24]:
X = df.drop("Survived", axis=1)       # feature matrix
y = df['Survived']

In [25]:
df1 = df.drop(columns=["Name", "Sex", "Ticket", "Cabin", "Embarked"])
df1.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [26]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='str')

In [27]:
df1['Age'].isnull().sum()

np.int64(177)

In [30]:
df1["Age"] = df1["Age"].ffill()

In [31]:
df1['Age'].isnull().sum()

np.int64(0)

In [32]:
feature=SelectKBest(mutual_info_classif,k=3)

In [33]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='str')

In [34]:
df1 = df1[["PassengerId", "Fare", "Pclass", "Age", "SibSp", "Parch", "Survived"]]
df1.head()

   PassengerId     Fare  Pclass   Age  SibSp  Parch  Survived
0            1   7.2500       3  22.0      1      0         0
1            2  71.2833       1  38.0      1      0         1
2            3   7.9250       3  26.0      0      0         1
3            4  53.1000       1  35.0      1      0         1
4            5   8.0500       3  35.0      0      0         0

In [35]:
X=df1.iloc[:,0:6]
y=df1.iloc[:,6]

In [36]:
X.columns

Index(['PassengerId', 'Fare', 'Pclass', 'Age', 'SibSp', 'Parch'], dtype='str')

In [37]:
y=y.to_frame()

In [38]:
y.columns

Index(['Survived'], dtype='str')

In [40]:
X = df1.drop("Survived", axis=1)       # feature matrix
y = df1['Survived']

In [41]:
feature.fit(X,y)

SelectKBest(k=3, score_func=<function mutual_info_classif at 0x7503d6466840>)

In [42]:
scores = pd.Series(feature.scores_, index=X.columns).sort_values(ascending=False)
selected = list(X.columns[feature.get_support()])
print("Feature scores (descending):")
print(scores)
print("Selected features:")
print(selected)

Feature scores (descending):
Fare           0.134069
Pclass         0.060343
Age            0.035182
Parch          0.018755
PassengerId    0.012241
SibSp          0.000000
dtype: float64
Selected features:
['Fare', 'Pclass', 'Age']